### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 123cdxcc** [Aruelius/wenshushu#3]
:~/wenshushu# python3 wss.py upload README.md
  File "wss.py", line 43
    print(f'文件过期时间:{days}天{hours}时{minutes}分{seconds}秒')
                                                      ^
SyntaxError: invalid syntax

**Comment by Aruelius** [comment]
需要 Python3.6 以上的版本哦

**Comment by 123cdxcc** [comment]
好
